{{- range $key, $value := .Values.issuersMap }}
---
apiVersion: cert-manager.io/v1
kind: {{ $value.kind }}
metadata:
  name: {{ $key }}
  {{- if $value.namespace }}
  namespace: {{ $value.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
spec:
  {{- toYaml $value.spec | trim | nindent 2 }}
{{- end }}
