{{- range $key, $value := .Values.ingressMap }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}
  {{- if $value.namespace }}
  namespace: {{ $value.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
    {{- if $value.annotations }}
    {{- toYaml $value.annotations | trim | nindent 4 }}
    {{- end }}
spec:
  {{- toYaml $value.spec | trim | nindent 2 }}
{{- end }}
