{{- range $key, $value := .Values.secretsMap }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  {{- if $value.namespace }}
  namespace: {{ $value.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
type: {{ $value.type }}
{{- if $value.stringData }}
stringData:
  {{- toYaml $value.stringData | trim | nindent 2 }}
{{- else if $value.data }}
data:
{{- range $key2, $value2 := $value.data }}
  {{ $key2 }}: {{ $value2 | trim | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
