bases:
  - .helmfile/environments.yaml.gotmpl
---
bases:
  - .helmfile/repositories.yaml
  - .helmfile/releases.yaml.gotmpl
helmDefaults:
  wait: true
  atomic: true
  devel: true
  createNamespace: true
