{{- range $key, $value := .Values.configsMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $key }}
  {{- if $value.namespace }}
  namespace: {{ $value.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
data:
  {{- toYaml $value.data | trim | nindent 2 }}
{{- end }}
