secrets-gitea:
    secretsMap:
        gitea-admin:
            type: ENC[AES256_GCM,data:L8UqGgzt,iv:PC/K0kQFY4UDtKR79mcc1+cKzitrIhwLSV8wBLsXjjs=,tag:w2yeK00o/x2EbFAtj4Xysg==,type:str]
            stringData:
                username: ENC[AES256_GCM,data:bYqiOLM=,iv:WDbgl8VgN7jAb33gkvpFkC1Bj4XIjLzl8bhOsft8QrU=,tag:fwTiAPUVcqzR/ztQHt51mA==,type:str]
                password: ENC[AES256_GCM,data:qK9Z7/M4zF9LF2ewLaXuv7I=,iv:fSvRk5yVZ6oKE0EyUhwJt81HI/Uguhk3H89ZG4ShDYk=,tag:zbjrY28gIZZN99vnMPhTSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-03T21:33:35Z"
    mac: ENC[AES256_GCM,data:7bQldqMv4rWPsrxNwbk6/nKl0rw2+038Xmjcj6YAOEQ5iGMH/eY/eFLBWEEjfDGzspt/+ilzsI1QAodqmT4aYsxxRg6k8TfXirkwOVURne6EeLM1ow5qgvm9I6M4lkznWkR7lM5taMF5tnsSzQcKNJTJJ7jOuIXyjImVq5ynW74=,iv:Su5zd0+QnuGFyALg6CyxneDYFcfsrwjIsJuZOXGmGLA=,tag:pRE5CZ7kd9uImiSzNKo8kQ==,type:str]
    pgp:
        - created_at: "2022-02-03T19:08:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyG9DnxrLu/QAQwApszE0nH/RPH919yQxstrWEs/45h4Fxt56c6Bhr1/v29g
            PpwF1AS74FMNW2HziDHuwTf+qqOE9GR+4q9N8c3aIqlShcWT9mvcZzMuelO0ytJO
            CG//7yaZpfLEeub1uGEgPBOCCAtYI/O8wuuBKZQkV+ppO6OR/Bn2p68Ktgq37F0h
            plkMp9dEb9aIFPTB/jqIv9gBsBFgZU47ArpU43as9SVtjY5N5dJJhj9STMb/FSoL
            z78fVoK++Z3z+thFr2EYMgaG6UH8SamuGzFqJ/FNdXAUzkOJPdP+bxvM6cQrAql2
            DMx7jboRqRZamRRY3DephHFyMDi71c9AYoITkjNL9JiTan8e13coOpJB5DNYEQra
            DA1LnE3v006rovus/R5gKZMzdsidRYvcWA26e0L+MTJgV0HtNBzwyxsX8e73TORJ
            FMhVdpO9GsHrJ6IJaSeOrb7QCpRZN3ryaeJ02iMmjQgfLW/NF2VqoERNd5L7KLBS
            4u0iXOjF0biELnLzY+ps0l4BmtTNZd7drBqDr61cfLHFPt+nM22lLXYe7sUllrRV
            VWZQeZKu0vQ50OqUdT0O8zD8mC4mH1GAF8VzUCwxS4JhqtxrC4+Gq3iSH2LizhKE
            pXq1pYU0J6biD0iAi6jI
            =WxE6
            -----END PGP MESSAGE-----
          fp: E7AAC91EEF6C253B72E8932519F0C91F73EFCA47
    unencrypted_suffix: _unencrypted
    version: 3.7.1
