secrets-gitea:
    secretsMap:
        gitea-admin:
            type: ENC[AES256_GCM,data:L8UqGgzt,iv:PC/K0kQFY4UDtKR79mcc1+cKzitrIhwLSV8wBLsXjjs=,tag:w2yeK00o/x2EbFAtj4Xysg==,type:str]
            stringData:
                username: ENC[AES256_GCM,data:bYqiOLM=,iv:WDbgl8VgN7jAb33gkvpFkC1Bj4XIjLzl8bhOsft8QrU=,tag:fwTiAPUVcqzR/ztQHt51mA==,type:str]
                password: ENC[AES256_GCM,data:qK9Z7/M4zF9LF2ewLaXuv7I=,iv:fSvRk5yVZ6oKE0EyUhwJt81HI/Uguhk3H89ZG4ShDYk=,tag:zbjrY28gIZZN99vnMPhTSQ==,type:str]
secrets-postfix:
    secretsMap:
        opendkim-keys:
            type: ENC[AES256_GCM,data:SuNxu1aL,iv:Xbzrq9FG6pOx5CCZPOj+nEJRF4HCB1JTdqesGvIr9Q0=,tag:ulGMmSPVMeNRj4hRBgXPyw==,type:str]
            stringData:
                zzamzam.dev.private: ENC[AES256_GCM,data:zqs6yCerMeXiOFKXuUazfSjXvoWkwNTSKe+b5Z5m5CLGSsX+eR9Ugv3lRWJqGiUdnVgNnVKvaSMp0wDKkfKuFAzyFEeNeG0sU5RpYw9FNWt1eYemEq3oWV7lb2JZ+YhW3pGiZU6X5BX2KuppYxENAza2xlBuyJz9LIwGT6owTxDKzdR6tGNSi+pggO50I+/34QC+kGeiKLDcgcW+kuNnWHv9qTpIEEuaXApbg/wmxWltWnhA88QlPv32uySFKqujg03U+Rzlpe6HgmRd+9XprBMhbrqdCX8pcPEvz1sHlQkmGROpk3w+w8CiV5Tc+HICXvuJapJdV1VgSAkDWVpcntlxUYvzWNEUNplFYUfmSE43LbMS4ZCOFJ6Il31pUqH582EsJt5LSgtEHqILnozgmnXE6Q9sk4rSn9NFamksdCC5AFTPKW8wm40OSpVsaEiVHZlwnxy+ka+W1ArSYWuLH0gSZfYfWrLXJsRUZWI5oiatg40/GMNFV4ArKiL+OCKdPrKptV35BXXbKv03sVixAEa/f8rzS3NO214FNEqpT05YX57PMzCozcjPmoABsTtIlX0XPj7onwOXFzGdXxS+rPVR4BR0fp03z8ltlZflEpSJEABIXtQP8OXxUxEMtb1AHeaQklm3hl2ZxQ4kPf8mSEj/qhOXQutcgmBDK8X4J+srQC5LTx/8PPSPe9xKj8ntsLUItPrd8Rwt/ZABVjk5AzaCd4oOzHN9cbkJNCYj4O/1KI30TvmgsKnECZI07JI2D3kGkn5TkGN3Q+czvhIPGgdpwckw7gPBnZiRDViyghdN4sReUbdZ8JbMAj8F2eqdrW+G7p7X8BtQ6fVoUH21M8hfTTXTzl/JQE+hBSx6JamH3K2f9xiEE9JVb8yTN5M6F1iYcSSnTbAr1vNC7kZ5xubIENjBjDvtK6qcDA5ZD5zHHQ00fjgRwh1DxpDjjCljJCgFRvjHFsaRmUt/K2Rk8pWETe7HEJ77pXlNWQatqHri0d3QiLhm+FREy1U7iBrekcN9srFweuVS41uXyOCF05cQO8ec3ICLzs+SCf9dZxJEy5ZkjXJoAvpNdP+0H/O4vYnGe0B3VWNt+CLm4z68TJILrLqkF+bhSO4DlGY6miH3rUQIIrlWlBx08F8/Jyn5j81JLHEyEZnGQ8ExbCwrN1uxY/SnIrYiJyy8CjkaZj6smEpTLFPl0reOvJeLMNsf4McZjHCcF6WmQ2ysfgKl+HKYsf+x0+Rf99IWI6EHnNq7flv1RyCIGJq2vnQ1HDI9sOZj4ZUPnOEZi4IwzF1BGEvVX8+euw2YwQOfAJa6DX1GwJoyx9wwToaQg+M4mwZiUE5dAREV+k1oDxO1igI/oGUP00dgfKWmiK4leXEauiE/Jr5I9eMCs/PM5v4ySWhCFtIZYZK1tk7f+4iWzCsmY7MRQKsnirJ83bDV/0dETTKmhTbzAhFRFnFDyg93vZkNs1118v9naL8CSowV4lTTqsvlGUd0bIbS5IHVjKiMkxiZ5m1ZBDJpCax7kfdFT2+w3avDEKeGhyGe8w5LxRG+TxkBhWezMP1XbIULDq6ynmCyS2uUq4dpH8HpZFmwW9Y10r+L9DJO/MoKRnEU78r1eJDuZ/LHVw2ahu4UsGhVSY/px7OaYDVZpr6urk6j1qwuDVQuL+cQb2DxgHnOEhca8AI5hLRMP75RfzdepTlmc6tCj9llptz96Pg07dIUPErF5WS5UBEB2WpWhsQpHGMfy0vEUHam2bZ/SdcXYH4eXVpkgGu/Qp7U2w8EQKw/PhezrmhRiu9C1XOKppSayqZtgXH2tYnxZgfYOKNC6YrLfknVmxLo9fn5uDKCRNFrmnl23FiU8LhhM9pY0U1m1mDVo5eYP3lvHjjXEHNK5o2regqZOnDN/ncRSuk/ZolP9kZD8lh2IeaLoXktUCexpqS4vA/H0Vi+GJT/btj8tbGPW8YCmGa1Yg0k+0qx9626aDwXw6M/ZjtGBzValgwKnmcLgfxC7IsxmvjShl6AfIFSm4lVgKlj6vCATExS73LTlZEl0RjfHvJNJPF6KUG6DxwEWNWXTY76QtYZDEto2BJnxaDL92FfvRv/SE3t3JoC40at9WMM1O6tThXSoiAgacZEFOe42nDOMoID7JrwC8Otm0S/UJekOyZf8g7/sOYJvTQtTkkc6T2GQa69IJEvtplQDquGEpsfG3kDn1Zk/tL9hPdJoU+RWRTLnUc5Ww==,iv:ZP9D4onIq+k/meRMgJPBIOStw+pzRzdx+/jnV+mFEu0=,tag:X2g7T2cUG6yOJZSRg9bMJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-05T20:46:54Z"
    mac: ENC[AES256_GCM,data:drgddr6YsiGMH1Q6EDP35snnIPxVDQ17xS74PzPpxb5cIjjyTXx8mMvY31rwdQvFnqSQLk15JsKndzkx+relHIA1enpma5H3zBdYld2Esk7ppix++l74GpyI818LbgwCg0IYN6xbAmdA+9Mcd7HowWxkntqfvg5imttGdDu6rLE=,iv:8hsE+9zTr8gJid71zsiPRwFetzc95ncJ6ZHleQL9Ehk=,tag:Cd6F/Qnnwag60mUYKiGRug==,type:str]
    pgp:
        - created_at: "2022-02-03T19:08:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyG9DnxrLu/QAQwApszE0nH/RPH919yQxstrWEs/45h4Fxt56c6Bhr1/v29g
            PpwF1AS74FMNW2HziDHuwTf+qqOE9GR+4q9N8c3aIqlShcWT9mvcZzMuelO0ytJO
            CG//7yaZpfLEeub1uGEgPBOCCAtYI/O8wuuBKZQkV+ppO6OR/Bn2p68Ktgq37F0h
            plkMp9dEb9aIFPTB/jqIv9gBsBFgZU47ArpU43as9SVtjY5N5dJJhj9STMb/FSoL
            z78fVoK++Z3z+thFr2EYMgaG6UH8SamuGzFqJ/FNdXAUzkOJPdP+bxvM6cQrAql2
            DMx7jboRqRZamRRY3DephHFyMDi71c9AYoITkjNL9JiTan8e13coOpJB5DNYEQra
            DA1LnE3v006rovus/R5gKZMzdsidRYvcWA26e0L+MTJgV0HtNBzwyxsX8e73TORJ
            FMhVdpO9GsHrJ6IJaSeOrb7QCpRZN3ryaeJ02iMmjQgfLW/NF2VqoERNd5L7KLBS
            4u0iXOjF0biELnLzY+ps0l4BmtTNZd7drBqDr61cfLHFPt+nM22lLXYe7sUllrRV
            VWZQeZKu0vQ50OqUdT0O8zD8mC4mH1GAF8VzUCwxS4JhqtxrC4+Gq3iSH2LizhKE
            pXq1pYU0J6biD0iAi6jI
            =WxE6
            -----END PGP MESSAGE-----
          fp: E7AAC91EEF6C253B72E8932519F0C91F73EFCA47
    unencrypted_suffix: _unencrypted
    version: 3.7.1
